import apiClient, { unwrap } from "./apiClient.js";

// Calculates payroll for a pay period from each employee's salary structure
// + LOP — no file involved (Module 5 v2 replaces the old CSV upload).
// Writes nothing; HR reviews this before calling confirmPayroll. `filters`
// (`role`/`profileStatus`, both optional) narrow which subtree members are
// included, so a run can be scoped to e.g. only VERIFIED employees.
export async function calculatePayroll(payPeriod, filters = {}) {
    const response = await apiClient.post("/salary-slips/calculate", { payPeriod, ...filters });
    return unwrap(response);
}

// Re-runs the same calculation server-side and commits it — never resends
// what calculatePayroll returned, since every figure is derived fresh from
// the DB state at confirm time (see salarySlipService.js on the server).
// `filters` must match whatever was passed to calculatePayroll for the
// preview being confirmed.
export async function confirmPayroll(payPeriod, filters = {}) {
    const response = await apiClient.post("/salary-slips/confirm", { payPeriod, ...filters });
    return unwrap(response);
}

export async function getMySalarySlips({ payPeriod } = {}) {
    const params = {};
    if (payPeriod) params.payPeriod = payPeriod;
    const response = await apiClient.get("/salary-slips/mine", { params });
    return unwrap(response);
}

// Paginated `{ slips, total }` — this list spans every payroll month ever
// run (200 employees x 36 months at NFR-7's target), so callers pass
// `limit`/`offset` alongside the filters. Same contract as the leave-request
// lists. `getMySalarySlips` stays unpaginated: that's one person's own ~36 rows.
export async function getSalarySlipsForHr(params = {}) {
    const response = await apiClient.get("/salary-slips", { params });
    return unwrap(response);
}

export async function getSalarySlipById(id) {
    const response = await apiClient.get(`/salary-slips/${id}`);
    return unwrap(response);
}

// Soft-deletes a slip generated by mistake (e.g. the wrong pay period) —
// marks it VOIDED rather than removing it, so there's a record it happened.
export async function voidSalarySlip(id, reason) {
    const response = await apiClient.post(`/salary-slips/${id}/void`, { reason });
    return unwrap(response);
}

// A plain URL, not an axios call — meant for an <a href download>. The
// server sets its own Content-Disposition: attachment header by default,
// same reasoning as leaveRequestService.getLeaveRequestDocumentDownloadUrl.
// Pass `{ inline: true }` instead for DocumentPreviewModal's <iframe> — the
// same stream, but with `Content-Disposition: inline`, so the browser
// renders it in the viewer instead of triggering a download the instant
// it's opened (the default `attachment` disposition forces a download
// regardless of how the URL is loaded, iframe included).
export function getSalarySlipPdfUrl(id, { inline = false } = {}) {
    const query = inline ? "?disposition=inline" : "";
    return `${apiClient.defaults.baseURL}/salary-slips/${id}/pdf${query}`;
}
